# Generated by Django 3.1.2 on 2020-11-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberID', models.AutoField(primary_key=True, serialize=False)),
                ('memberName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('homeID', models.AutoField(primary_key=True, serialize=False)),
                ('homeName', models.CharField(max_length=30)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozenDuty_app.member')),
            ],
            options={
                'unique_together': {('homeID', 'memberID')},
            },
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('groceryID', models.AutoField(primary_key=True, serialize=False)),
                ('groceryName', models.CharField(max_length=50)),
                ('unitPrice', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('purchaseDate', models.DateField()),
                ('ExpirationDate', models.DateField()),
                ('ItemType', models.CharField(max_length=30)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozenDuty_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('choreID', models.AutoField(primary_key=True, serialize=False)),
                ('choreName', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('dueDate', models.DateField()),
                ('status', models.CharField(max_length=5)),
                ('steps', models.IntegerField(default=1)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozenDuty_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('groceryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dozenDuty_app.grocery')),
                ('homeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozenDuty_app.home')),
            ],
            options={
                'unique_together': {('groceryID', 'homeID')},
            },
        ),
        migrations.CreateModel(
            name='Does',
            fields=[
                ('choreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dozenDuty_app.chore')),
                ('homeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozenDuty_app.home')),
            ],
            options={
                'unique_together': {('choreID', 'homeID')},
            },
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dozenDuty_app.member')),
                ('homeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dozenDuty_app.home')),
            ],
            options={
                'unique_together': {('memberID', 'homeID')},
            },
        ),
    ]
