# Generated by Django 3.1.2 on 2020-11-05 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dozenDuty_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='ItemType',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='memberID',
        ),
        migrations.AddField(
            model_name='grocery',
            name='memberName',
            field=models.CharField(default='Sean', max_length=50),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='ExpirationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='purchaseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
