# Generated by Django 3.1.2 on 2020-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozenDuty_app', '0002_auto_20201105_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='ItemType',
            field=models.CharField(default='Grocery', max_length=30),
            preserve_default=False,
        ),
    ]
